travis:
  secure:
    BINSTAR_TOKEN: n9HdVp+mv536wFkx0fcEwJggD+DUiPgYSG9GwqkjnuAFIO49rN9ubX61fRx8oyGPITx8AxrOlawjZr9eQMG1c6GaoyMO5xEMzVbhIeduNO9A+7Ye4f1hb+3G+3a5LWYaMogodHM3bwkn63/wgshqSq3lHG5l7AMm4PYZyPGn1k8R1VEzt4jPQIS3TYOv12U8y4C2I3AR01iRBnwxBVkrntKw9U6QJQUleAVQMJPRtzFkaThJohRqN5xCOurIhD6CCqUtc6KydVJeGvCgSfDMJxRKUv65h71BnwQaZOWNb9cV/p0B6uUI35t5FlD8g5qQe9hnqrcENc5UXCchw3eenKMseyas/SIWnnVoi7ewdt7RLFA1xB9dPjPTytr8xTEmOtEepjQ2cmExDNJ2DSOB7B9qMNYqgH5XH90naz/u7nT0Bg/HDHRNABGhMNUCJ6QR/Ezyt9mYQXqcgf8NylFZSZO0QOi4o8DSI9zixBrjNMxbyRSFRlLX24Raybcmu/2ha7/HAvD235b2QLgTlibDkErDf89EwT/AV74jX+v4/bL2vu5S0XkDAzFStq2HfavA8T4heoyFuDUaUsXk6upMYmZXkMKKqR0cPCk2yP6hqXexQ4GwcEgYhDlg485fipvcafKMVByeUI57lhKIpdKGgZwgzCWQQHGVKcO9E1aE15A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
