travis:
  secure:
    BINSTAR_TOKEN: pqVky2IUPBCaa6Oeg3TJx0yQysWJYSLJlZ3zg2WmZ/+grCSN9zx+4znVr1JDhLDhSkKMitqV3nDXC3M1EfGWtwfR6JRlTS069SPhC8d0ad49G71vv9AlUJlYMsbIuRHdQUhsg7TOarOmfPFGd4krVo3GaptKXRkQ17I2yc6rH9oUG/+gl/iefzXlQdWCFMuiNQrzu/huqWTjdxZS+YTPsoEZRQNY5VGOo6IDLUqDlenZNg+iDqPm3cJlc4eYpqIHFNEYZF0zqfqAjPYSks0ASF5ihVkzTP1bKrJ6ApAKI/3wkdnXy+09+yTxHsjSpTcHFPtojM0c7TCf/DdGuAuodyAzUqQI+dM074nWNfacymvTTDa7fwkhKIO6vqhVEthhryYSyfj23/isImPijkqL3WmD201MLBMiQ4xsHDZM6ZyBU0IzP0Ck/q1nyVIUlR8aalLG5TyFEpg9XTfyl+Om69jActEEto9KffM1Daas3qUFudOGeOUvqHlRlzzk4GSOGxpNjlVVIz3jGVme7L+oKP0dCSLZm/0dYzqcgCQB7BK2dkHH24JTvYNLb9gAG5gEJg0ccMEIX0ZoOkVtswXhG050efKVBCvjwWvcbh/zZavzVf9x9A+KqA8u+ugo4Jpf0KomuMSjCCYlQNOM9CBiuOgLg3if2nvo7Xjt9pVr3xY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
